# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4001c499c9546120a046a3463c0968f01a37c5ed124f7c25119dc1d8a3002bb1da530e6abbbb29bd950363268ac9b56ea5e6cba75b2341ff4b2c902ed98f3c4

test:
  secret_key_base: 394d69a8857996244e8f01798293cd30cccbafb98c120d6a9a5f5334c1efdf51c3151682b61d62a234fdc45b36986ac9425dcf8c2e17375dc923e87581dfb169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
